--[[
    init.lua
    Created: 07/30/2023 22:52:14
    Description: Autogenerated script file for the map partnerIntroScene.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local partnerIntroScene = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---partnerIntroScene.Init(map)
--Engine callback function
function partnerIntroScene.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

  local player = CH('PLAYER')
  local partnerSpecies = getPartnerSpecies(player)

  setMiracleGroundCharSpec(partnerSpecies)


end

---partnerIntroScene.Enter(map)
--Engine callback function
function partnerIntroScene.Enter(map)

  local player = CH('PLAYER')

  local miracle = CH('Miracle')

  GAME:CutsceneMode(true)
  
  GAME:MoveCamera(225, 275, 1, false)

  GAME:FadeIn(20)

  UI:SetSpeaker(miracle)
  UI:WaitShowDialogue("Hello...? Helloooo??? You're not dead, are you?")
  UI:WaitShowDialogue("Oh Arceus- I was so worried... You gave me a heart attack!")
  UI:WaitShowDialogue("Can you walk? I- I can carry you back somewhere safe if you need me to!")
  
  UI:SetSpeaker(player)
  UI:WaitShowDialogue("What...? No- No, I'm fine, I'm okay. Who...? Wh--")
  UI:WaitShowDialogue("WHAAAAAAAAAAAAAAAT?")

  UI:SetSpeaker(miracle)
  UI:WaitShowDialogue("Woah woah WOAH!! Calm down, what happened?!?")

  UI:SetSpeaker(player)
  UI:WaitShowDialogue("I- I was in front of a car-- And- And--?!")

  UI:SetSpeaker(miracle)
  UI:WaitShowDialogue("Oh, Gods- You look so scared- Don't worry, I can help you out! My name is-")

  UI:NameMenu("My Name is...", "Your new friend's name cannot be changed. The default name is 'Miracle'.", 48)
  UI:WaitForChoice()
  local mon_id = RogueEssence.Dungeon.MonsterID(getPartnerSpecies(player), 0, "normal", Gender.Genderless)
  local p = _DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, mon_id, 5, "", 0)
  local tbl = LTBL(p)
  tbl.Importance = 'Partner'
  p.IsFounder = true
  p.IsPartner = true
  local partnerName = UI:ChoiceResult()
  if (partnerName == "") then
    p.Nickname = 'Miracle'
  else
    p.Nickname = UI:ChoiceResult()
   end
  
  _DATA.Save.ActiveTeam.Players:Add(p)


  UI:WaitShowDialogue(p.Nickname .. "! Come on, I know a path-- BAAAAACK?!")

  GAME:CutsceneMode(false)

  GAME:EnterDungeon('ruined_lab', 0, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, true, false)

end

---partnerIntroScene.Exit(map)
--Engine callback function
function partnerIntroScene.Exit(map)


end

---partnerIntroScene.Update(map)
--Engine callback function
function partnerIntroScene.Update(map)


end

---partnerIntroScene.GameSave(map)
--Engine callback function
function partnerIntroScene.GameSave(map)


end

---partnerIntroScene.GameLoad(map)
--Engine callback function
function partnerIntroScene.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-------------------------------
-- Extra Map Calls
-------------------------------

function getPartnerSpecies(player)
  local plSpec = player.CurrentForm.Species

  if(plSpec == "turtwig") then
    return "squirtle"
  elseif(plSpec == "litten") then
    return "glameow"
  elseif(plSpec == "oshawott") then
    return "shroomish"
  elseif(plSpec == "purrloin") then
    return "shinx"
  elseif(plSpec == "chikorita") then
    return "scorbunny"
  elseif(plSpec == "mudkip") then
    return "mareep"
  elseif(plSpec == "minccino") then
    return "skiddo"
  elseif(plSpec == "fennekin") then
    return "buizel"
  elseif(plSpec == "cyndaquil") then
    return "chespin"
  elseif(plSpec == "growlithe") then
    return "electrike"
  elseif(plSpec == "eevee") then
    return "deerling"
  elseif(plSpec == "snivy") then
    return "totodile"
  elseif(plSpec == "zorua") then
    return "vulpix"
  elseif(plSpec == "treecko") then
    return "froakie"
  elseif(plSpec == "popplio") then
    return "chimchar"
  elseif(plSpec == "piplup") then
    return "torchic"
  end
end

function setMiracleGroundCharSpec(species)
  local miracle_ground = CH('Miracle')
  local miracleId = RogueEssence.Dungeon.MonsterID(miracle_ground.CurrentForm.Species, miracle_ground.CurrentForm.Form, "normal", Gender.Unknown)
  miracle_ground.Data.BaseForm = RogueEssence.Dungeon.MonsterID(species, 0, "normal", Gender.Unknown)

end
    

return partnerIntroScene

