--[[
    init.lua
    Created: 08/03/2023 16:51:59
    Description: Autogenerated script file for the map placeholder_ruined_checkpoint.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local placeholder_ruined_checkpoint = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---placeholder_ruined_checkpoint.Init(map)
--Engine callback function
function placeholder_ruined_checkpoint.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  
  COMMON.RespawnAllies()
end

---placeholder_ruined_checkpoint.Enter(map)
--Engine callback function
function placeholder_ruined_checkpoint.Enter(map)

  GAME:FadeIn(20)

end

---placeholder_ruined_checkpoint.Exit(map)
--Engine callback function
function placeholder_ruined_checkpoint.Exit(map)


end

---placeholder_ruined_checkpoint.GameLoad(map)
--Engine callback function
function placeholder_ruined_checkpoint.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Object Callbacks
-------------------------------

function placeholder_ruined_checkpoint.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function placeholder_ruined_checkpoint.Teammate2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end


return placeholder_ruined_checkpoint

