--[[
    init.lua
    Created: 07/21/2023 09:10:06
    Description: Autogenerated script file for the map temporal_pinnacle.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local temporal_pinnacle = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---temporal_pinnacle.Init(map)
--Engine callback function
function temporal_pinnacle.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---temporal_pinnacle.Enter(map)
--Engine callback function
function temporal_pinnacle.Enter(map)
  --Find actors by name
  local dialga = CH('Dialga')
  local yveltal = CH('YVELTAL')
  local player = CH('PLAYER')

  --set the game to cutscene mode to prevent idle animations
  GAME:CutsceneMode(true)

  -- show the title of the ground map, take 20 frames to do so.
  UI:WaitShowTitle(GAME:GetCurrentGround().Name:ToLocal(), 20);
  GAME:WaitFrames(30);
  --fade out title, 20 frames
  UI:WaitHideTitle(20);

  --move the camera to a center at X248, Y216. Single frame. Don't focus on player (False)
  GAME:MoveCamera(276, 264, 1, false)

  -- fade in, 20 frames
  GAME:FadeIn(20)

  --Move the player up to position X240, Y248, Don't use running animation. Speed of 2.
  GROUND:MoveToPosition(player, 268, 296, false, 2)

  --Dialga Speaks
  UI:SetSpeaker(dialga)
  UI:WaitShowDialogue("...")
  UI:WaitShowDialogue("... UNDER NORMAL CIRCUMSTANCES, I WOULD NOT SEE TO YOU.")
  UI:WaitShowDialogue("THAT RESPONSIBILITY FALLS TO YVELTAL.")
  UI:WaitShowDialogue("YET, THIS IS A SPECIAL CASE. IT SEEMS YVELTAL HAS SEEN SOMETHING IN YOU.")
  UI:WaitShowDialogue("SOMETHING NECESSARY.")
  UI:WaitShowDialogue("AS SUCH, I WILL BE PROVIDING THEM ASSISTANCE IN ALTERING THE 'NORMAL CIRCUMSTANCES.'")
  UI:WaitShowDialogue("THEY HAVE ASKED TO SPEAK TO YOU.")
  UI:WaitShowDialogue("MAKE YOUR DECISIONS WISELY.")
  
  --Play rear up animation and hold the pose
  local animId = RogueEssence.Content.GraphicsManager.GetAnimIndex("RearUp")
  GROUND:CharSetAction(dialga, RogueEssence.Ground.PoseGroundAction(dialga.Position,dialga.Direction, animId))
  SOUND:PlayBattleSE("EVT_Roar")
  
  --Screen Shake: Minimum of 0px, max of 8px. Starts at 8, with 30 frames go from 8 to 0.
  GROUND:MoveScreen(RogueEssence.Content.ScreenMover(0,8,30))
  GAME:WaitFrames(60)
  
  --fade
  SOUND:PlayBattleSE("EVT_Battle_Transition")
  --Fade out, white fade set to true, taking 80 frames
  GAME:FadeOut(true,80)

  GAME:WaitFrames(30)

  UI:SetSpeaker(yveltal)
  UI:WaitShowDialogue("Do not worry.")
  UI:WaitShowDialogue("Even if this weren't an unusual circumstance, you would be safe here.")
  UI:WaitShowDialogue("I'm sure you're very confused.")
  UI:WaitShowDialogue("It will take time to understand, and I cannot explain it all to you.")
  UI:WaitShowDialogue("But you are very important. For both here and there.")
  UI:WaitShowDialogue("You may feel a bit disoriented at first. That is normal.")
  UI:WaitShowDialogue("You will learn rather quickly.")
  UI:WaitShowDialogue("I believe my time to speak to you is limited, though. So please. Be careful.")
  UI:WaitShowDialogue("And choose wisely.")

  GAME:CutsceneMode(false)

  --Wait
  GAME:WaitFrames(20)

  --Enter Partner Intro Scene
  GAME:EnterZone("ruined_lab", -1, 0, 0)

end

---temporal_pinnacle.Exit(map)
--Engine callback function
function temporal_pinnacle.Exit(map)


end

---temporal_pinnacle.Update(map)
--Engine callback function
function temporal_pinnacle.Update(map)


end

---temporal_pinnacle.GameSave(map)
--Engine callback function
function temporal_pinnacle.GameSave(map)


end

---temporal_pinnacle.GameLoad(map)
--Engine callback function
function temporal_pinnacle.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return temporal_pinnacle

